### ISSUE TITLE
hls format 

### ISSUE THREAD

**Issue by YanivPlaybuzz** [zencoder/zencoder-node#6]
hey guys, i m using your package and would like to know what should i specify in the output object so i could provide an mp4 url as an input, and get my link converted to m3u8 and uploaded to mmy configured cloud.
thats what i currently have: 
Job.create({
        input: videoUrl,
        outputs: [{
          url: videoOutputUrl
        }]}, function(err, data) {});

**Comment by chriswarren** [comment]
Check out the documentation at https://support.brightcove.com/zencoder-http-live-segmented-streaming-and-playlists for some example requests for HLS outputs.
